<html xmlns:py="http://genshi.edgewall.org/" xmlns:xi="http://www.w3.org/2001/XInclude" py:strip="">


<py:def function="announcement_id">
PMASA-2005-4
</py:def>

<py:def function="announcement_date">
2005-10-11
</py:def>


<py:def function="announcement_summary">
Local file inclusion vulnerability
</py:def>


<py:def function="announcement_description">
In <tt>libraries/grab_globals.lib.php</tt>, the <tt>$$__redirect</tt> parameter was not correctly validated, opening the door to a local file inclusion attack.
</py:def>


<py:def function="announcement_severity">
We consider this vulnerability to be serious. However, it can be exploited only on systems not running in PHP safe mode (unless a deliberate hole was opened by including in open_basedir some paths containing sensitive data).
</py:def>


<py:def function="announcement_affected">
phpMyAdmin versions 2.6.4 and 2.6.4-pl1.
</py:def>


<py:def function="announcement_solution">
Upgrade to phpMyAdmin 2.6.4-pl2 or newer.
</py:def>

<py:def function="announcement_cve">
CVE-2005-3299
</py:def>


<xi:include href="_page.tpl" />
</html>
