<html xmlns:py="http://genshi.edgewall.org/" xmlns:xi="http://www.w3.org/2001/XInclude" py:strip="">

<py:def function="announcement_id">
PMASA-2014-14
</py:def>

<py:def function="announcement_date">
2014-11-?
</py:def>


<py:def function="announcement_summary">
Local file inclusion vulnerability.
</py:def>


<py:def function="announcement_description">
In the GIS editor feature, a parameter specifying the geometry type was not correcly validated, opening the door to a local file inclusion attack.
</py:def>


<py:def function="announcement_severity">
We consider this vulnerability to be serious.
</py:def>

<py:def function="announcement_mitigation">
This vulnerability can be triggered only by someone who is logged in to phpMyAdmin, as the usual token protection prevents non-logged-in users from accessing the required page.
</py:def>


<py:def function="announcement_affected">
Versions 4.0.x (prior to 4.0.10.6), 4.1.x (prior to 4.1.14.7) and 4.2.x (prior to 4.2.?) are affected.
</py:def>


<py:def function="announcement_solution">
Upgrade to phpMyAdmin 4.0.10.6 or newer, or 4.1.14.7 or newer, or 4.2.? or newer, or apply the patch listed below. 
</py:def>

<py:def function="announcement_references">
?
</py:def>

<py:def function="announcement_commits_4_1">
?
</py:def>

<py:def function="announcement_commits_4_0">
2e3f0b9457b3c8f78beb864120bd9d55617a11b5
</py:def>

<py:def function="announcement_cve">CVE-2014-?</py:def>

<py:def function="announcement_cwe">661 98</py:def>

<xi:include href="_page.tpl" />
</html>
