<!--! Template for security announcement -->
<html xmlns:py="http://genshi.edgewall.org/" xmlns:xi="http://www.w3.org/2001/XInclude" py:strip="">


<py:def function="announcement_id">
PMASA-2011-10
</py:def>

<py:def function="announcement_date">
2011-07-23
</py:def>

<py:def function="announcement_summary">
Local file inclusion.
</py:def>

<py:def function="announcement_description">
Via a crafted MIME-type transformation parameter, an attacker can perform a local file inclusion.
</py:def>

<py:def function="announcement_severity">
We consider this vulnerability to be serious.
</py:def>

<py:def function="announcement_mitigation">
The phpMyAdmin's configuration storage mechanism must be configured for this attack to work.
</py:def>

<py:def function="announcement_affected">
Versions 3.4.0 to 3.4.3.1 are affected.
</py:def>

<py:def function="announcement_solution">
Upgrade to phpMyAdmin 3.4.3.2 or apply the related patch listed below.
</py:def>

<!--! Links to reporter etc, do not forget to escape & to &amp; -->
<py:def function="announcement_references">
This issue was found by Norman Hippert from <a href="http://www.the-wildcat.de/">The-Wildcat.de</a>
</py:def>

<!--! CVE ID of the report, this is automatically added to references -->
<py:def function="announcement_cve">CVE-2011-2643</py:def>

<py:def function="announcement_cwe">661 98</py:def>

<py:def function="announcement_commits">
f63e1bb42a37401b2fdfcd2e66cce92b7ea2025c
</py:def>

<xi:include href="_page.tpl" />
</html>
