<!--! Template for security announcement -->
<html xmlns:py="http://genshi.edgewall.org/" xmlns:xi="http://www.w3.org/2001/XInclude" py:strip="">


<py:def function="announcement_id">
PMASA-2011-3
</py:def>

<py:def function="announcement_date">
2011-05-22
</py:def>

<py:def function="announcement_summary">
XSS vulnerability on Tracking page.
</py:def>

<py:def function="announcement_description">
It was possible to create a crafted table name that leads to XSS. 
</py:def>

<py:def function="announcement_severity">
We consider this vulnerability to be serious.
</py:def>

<py:def function="announcement_mitigation">
This vulnerability works in the context of a shared phpMyAdmin installation.
The attacker needs to convince a victim to go to the Tracking page that
relates to the crafted table.
</py:def>

<py:def function="announcement_affected">
The 3.3.x and 3.4.0 versions are affected.
</py:def>

<py:def function="announcement_solution">
Upgrade to phpMyAdmin 3.3.10.1 or 3.4.1 or apply the related patch listed below.
</py:def>

<!--! Links to reporter etc, do not forget to escape & to &amp; -->
<py:def function="announcement_references">
This issue was found by a person who wishes to be known as "dave b". 
</py:def>

<!--! CVE ID of the report, this is automatically added to references -->
<py:def function="announcement_cve">CVE-2011-1940</py:def>

<py:def function="announcement_cwe">661 79</py:def>

<py:def function="announcement_commits">
7e10c132a3887c8ebfd7a8eee356b28375f1e287
d3ccf798fdbd4f8a89d4088130637d8dee918492
</py:def>

<py:def function="announcement_commits_3_3_10">
1300510d3686b40adefafb7f1778a6f06d0a553a
452669a1746898a08129d3a555ac4b1ec084b423
</py:def>

<xi:include href="_page.tpl" />
</html>
