<html xmlns:py="http://genshi.edgewall.org/" xmlns:xi="http://www.w3.org/2001/XInclude" py:strip="">

<py:def function="announcement_id">
PMASA-2010-8
</py:def>

<py:def function="announcement_date">
2010-11-29
</py:def>

<py:def function="announcement_summary">
XSS attack in database search.
</py:def>

<py:def function="announcement_description">
It was possible to conduct a XSS attack using spoofed request on the db search script.
</py:def>

<py:def function="announcement_severity">
We consider this vulnerability to be non critical.
</py:def>

<py:def function="announcement_affected">
For 3.x: versions before 3.3.8.1 are affected. For 2.11.x: versions before 2.11.11.1 are affected.
</py:def>

<py:def function="announcement_solution">
Upgrade to phpMyAdmin 3.3.8.1 or newer, or 2.11.11.1 if using the 2.11.x family. You can also apply the patch listed below.
</py:def>

<py:def function="announcement_references">
Thanks to Alexander Opitz for reporting this issue.
</py:def>

<py:def function="announcement_cve">CVE-2010-4329</py:def>

<py:def function="announcement_cwe">661 79</py:def>

<py:def function="announcement_commits">
4341818d73d454451f024950a4ce0141608ac7f8
</py:def>

<py:def function="announcement_commits_2_11">
e1f4901ffc400b6d2df15eac0ba5015fe48a27c4
</py:def>

<xi:include href="_page.tpl" />
</html>
