<html xmlns:py="http://genshi.edgewall.org/" xmlns:xi="http://www.w3.org/2001/XInclude" py:strip="">

<py:def function="announcement_id">
PMASA-2006-4
</py:def>

<py:def function="announcement_date">
2006-06-30
</py:def>

<py:def function="announcement_updated">
2006-07-01
</py:def>

<py:def function="announcement_summary">
XSS vulnerability
</py:def>


<py:def function="announcement_description">
It was possible to craft a request that contains XSS by attacking the &quot;table&quot; parameter. 
</py:def>


<py:def function="announcement_severity">
We consider this vulnerability to be serious.
</py:def>


<py:def function="announcement_affected">
Some versions previous to 2.8.2 suffer from this vulneribility.
</py:def>

<py:def function="announcement_solution">
Upgrade to phpMyAdmin 2.8.2.
</py:def>

<py:def function="announcement_references">
We wish to thank bug@securitynews.ir for informing us in a responsible manner. Their advisory is located at <a href="http://securitynews.ir/advisories/phpmyadmin281.txt">http://securitynews.ir/advisories/phpmyadmin281.txt</a>.
</py:def>

<py:def function="announcement_cve">CVE-2006-3388</py:def>

<xi:include href="_page.tpl" />
</html>
