<html xmlns:py="http://genshi.edgewall.org/" xmlns:xi="http://www.w3.org/2001/XInclude" py:strip="">

<py:def function="announcement_id">
PMASA-2011-15
</py:def>

<py:def function="announcement_date">
2011-10-17
</py:def>

<py:def function="announcement_summary">
Path disclosure due to insufficient url parameter validation.
</py:def>

<py:def function="announcement_description">
When the js_frame parameter of phpmyadmin.css.php is defined as an array,
an error message shows the full path of this file,
leading to possible further attacks.
</py:def>

<py:def function="announcement_mitigation">
For the error messages to be displayed, php.ini's error_reporting must be set 
to E_ALL and display_errors must be On (these settings are not recommended 
on a production server in the PHP manual).
</py:def>

<py:def function="announcement_severity">
We consider this vulnerability to be non critical.
</py:def>

<py:def function="announcement_affected">
Versions 3.4.x are affected.
</py:def>

<py:def function="announcement_solution">
Upgrade to phpMyAdmin 3.4.6 or newer or apply the related patch listed below.
</py:def>

<py:def function="announcement_references">
Thanks to <a href="http://securitate.md/">Mihail Ursu</a> for reporting this issue.
</py:def>

<py:def function="announcement_cve">CVE-2011-3646</py:def>

<py:def function="announcement_cwe">20 200</py:def>

<py:def function="announcement_commits">
d35cba980893aa6e6455fd6e6f14f3e3f1204c52
</py:def>

<py:def function="announcement_commits_3_4">
e05b37d3c9e5b99e8a779fe55780d92df17b4a55
</py:def>

<xi:include href="_page.tpl" />
</html>
